[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opinf"
description = "Operator Inference for data-driven model reduction of dynamical systems."
dynamic = [
    "version",
]
authors = [
    {name = "Willcox Research Group", email = "kwillcox@oden.utexas.edu"},
]
maintainers = [
    {name = "Shane A. McQuarrie", email = "shanemcq@utexas.edu"},
]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = [
    "operator inference",
    "model reduction",
    "scientific machine learning",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "Development Status :: 4 - Beta",
]
dependencies = [
    "h5py>=2.9.0",
    "numpy>=1.16",
    "scipy>=1.3",
    "matplotlib>=3.0",
    "scikit-learn>=0.18",
]

[project.optional-dependencies]
tests = [
    "pytest>=6.0.2",
    "pytest-cov>=2.12.1",
    "flake8>=3.9.0",
]
docs = [
    "jupyter-book>=0.14.0,<0.15.0",
    "numpydoc>=1.2",
    "sphinx-design>=0.1.0",
    "sphinxcontrib-mermaid>=0.7.1",
]

[project.urls]
homepage = "https://willcox-research-group.github.io/rom-operator-inference-Python3/source/index.html"
documentation = "https://willcox-research-group.github.io/rom-operator-inference-Python3/source/index.html"
repository = "https://github.com/Willcox-Research-Group/rom-operator-inference-Python3.git"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.setuptools.dynamic]
version = {attr = "opinf.__version__"}
