# post/__init__.py
r"""Tools for computing errors of reduced-order model solutions.

.. currentmodule:: opinf.post

Absolute and Relative Error
===========================

Given a norm :math:`\|\cdot\|`, "true" data :math:`\Q`, and an
approximation :math:`\breve{\Q}` to :math:`\Q`, the absolute
and relative errors of the approximation :math:`\breve{\Q}` are defined
as

.. math::
    e_{\text{absolute}}
    = \|\Q - \breve{\Q}\|,
    \qquad
    e_{\text{relative}}
    = \frac{e_{\text{absolute}}}{\|\Q\|}
    = \frac{\|\Q - \breve{\Q}\|}{\|\Q\|}.

In the context of this package, :math:`\Q\in\RR^{n \times k}` is
typically a matrix whose :math:`j`th column is the true state vector at time
:math:`t_{j}`, and the approximation :math:`\breve{\Q}\in\RR^{n
\times k}` is the corresponding matrix of reduced-order model solutions.

Projection Error
================

The projection error is defined by the low-dimensional representation of the
state, not the solution of a reduced-order model *per se*. For a true state
:math:`\q \in \RR^{n}`, consider the  low-dimensional (linear)
approximation

.. math::
    \breve{\q} = \Vr\qhat,

where :math:`\Vr\in\RR^{n\times r}`. The projection error
associated with this approximation is

.. math::
    \|\q - \breve{\q}\|
    = \|\q - \Vr\Vr\trp\q\|.

The following function computes this projection error, given a basis matrix
:math:`\Vr`.

.. autosummary::
    :toctree: _autosummaries
    :nosignatures:

    projection_error

This function is also available as :func:`opinf.pre.projection_error`; basis
classes such as :class:`opinf.pre.PODBasis` also have a ``projection_error()``
method.

Reduced-order Model Error
=========================

The following functions compute the error between a true state solution
:math:`\q(t) \in \RR^{n}` of the system of interest and an
approximation :math:`\breve{\q}(t) \in \RR^{n}` generated by
a reduced-order model.
Each uses a different norm to measure the absolute and relative errors.

.. autosummary::
    :toctree: _autosummaries
    :nosignatures:

    frobenius_error
    lp_error
    Lp_error
"""

from ._errors import *
